
---
title: "`HDF5DataFrame`"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
package: "`r BiocStyle::pkg_ver('HDF5DataFrame')`"
author: 
  - name: Artur Manukyan
output:
  BiocStyle::html_document
vignette: |
  %\VignetteIndexEntry{HDF5DataFrame}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

HDF5-backed DataFrame objects and methods. 

```{r load-libs}
library(rhdf5)
library(HDF5Array)
library(HDF5DataFrame)
```

# Installation

You can install `r Biocpkg("HDF5DataFrame")` from Bioconductor using 
**BiocManager**:

```{r bioc, eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}
BiocManager::install("HDF5DataFrame")
```

Or you can install the development version of `r Biocpkg("HDF5DataFrame")` 
from GitHub like so:

```{r devtools, eval=FALSE}
if (!require("devtools", quietly = TRUE))
    install.packages("devtools")
devtools::install_github("BIMSBbioinfo/HDF5DataFrame")
```

# Usage

The main usage of the HDF5DataFrame is to deliver DelayedArray 
operations for DataFrames

```{r read}

# create h5 and a group for the hdf5 backed data frames
output_h5ad <- tempfile(fileext = ".h5")

# data
data("chickwts")
metadata <- chickwts

# create HDF5DataFrame and write to hdf5
metadata_hdf5 <- writeHDF5DataFrame(metadata,
                                    filepath = output_h5ad, 
                                    name = "metadata",
                                    replace = TRUE)

# view HDF5DataFrame
metadata_hdf5
```

# Methods

```{r methods}
# cbind with in memory data
metadata_hdf5 <- cbind(metadata_hdf5, metadata)
metadata_hdf5
```

```{r methods2}
# coerce to data.frame
metadata_hdf5 <- as.data.frame(metadata_hdf5)
head(metadata_hdf5)
```

# Session info

```{r sessionInfo, echo=FALSE}
sessionInfo()
```